# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      # 系统库 数据源
      datasource:
        master:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=AGMES.SYS;SelectMethod=cursor;trustServerCertificate=true  #SelectMethod=cursor新增
          username: sa
          password: root
        # 业务 数据源
        service:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          # 数据源开关/默认关闭
          url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=AGMES.BASIC;SelectMethod=cursor;trustServerCertificate=true
          username: sa
          password: root
        # 业务 数据源
        param:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=AGMES.PARAM;SelectMethod=cursor;trustServerCertificate=true
          username: sa
          password: root
        # 日志 数据源
        log:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=AGMES.LOG;SelectMethod=cursor;trustServerCertificate=true
          username: sa
          password: root
        # 报表 数据源
    #                report:
    #                    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #                    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=AGMES.REPORT;SelectMethod=cursor;trustServerCertificate=true
    #                    username: sa
    #                    password: qq2504010089
    druid:
      # 初始连接数
      initialSize: 10
      # 最小连接池数量
      minIdle: 20
      # 最大连接池数量
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: mes
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
      #连接出错后再尝试连接三次
      connection-error-retry-attempts: 3
      #超过时间限制是否回收
      remove-abandoned: true
      #超时时间；单位为秒。180秒=3分钟
      remove-abandoned-timeout: 20
      #关闭abanded连接时输出错误日志
      log-abandoned: false
